### ISSUE TITLE
Should we allow for a group/resource "singular" name to match another group/resource "plural" name?

### ISSUE THREAD

**Issue by duglin** [xregistry/spec#277]
E.g.
```
Group1:
  - Plural: schemagroups
  - Singular: schemagroup
Group2:
  - Plural: schemagroup
  - Singular: items 
```

Conceptually/technically, there should be no reason to block it.
However, are we asking for trouble:
```
GET /schemagroups/foo
GET /schemagroup/foo
```
Or should we let the user confuse themselves?
